package textui;

/**
 * A list of all labels for prompts, must work together with (language)/ms.txt
 */
public enum PresenterPrompts {
    pressEnterToContinue,
    pressEnterToShowAnswer,

    /*friend related prompts*/
    chooseUserToAddFriendPrompt,
    friendAddFailed,
    friendAddSucceeded,

    chooseOptionWithQuitPrompt,
    chooseOptionPrompt,
    chooseStudyToolToEditPrompt,
    chooseStudyToolToStudyPrompt,
    chooseStudyToolToDeletePrompt,
    chooseStudyToolToUndeletePrompt,
    chooseUserToSuspend,
    chooseNumberOfDaysToSuspend,
    saySuspensionSuccess,
    sayProgramFrozenFor,
    suspendAnotherUserPrompt,
    chooseQuestionNumberToEditPrompt,
    chooseTemplatePrompt,

    newQuestionPrompt,
    newQuestionWithQuitPrompt,
    newAnswerPrompt,
    getAnswerPrompt,
    getFCAnswerPrompt,
    templateIDPrompt,
    saveOrNotPrompt,
    setStudyToolNamePrompt,
    setAccessibilityPrompt,
    editNameGenericPrompt,

    // Template editor options
    templateEditorunfamiliarFCReappear,
    templateEditortemplateScored,
    templateEditorTemplateTimedMenu,
    templateEditorTemplateTimed,
    templateEditorTemplateTimedPerQuestion,
    templateEditorTemplateTimeLimit,
    templateEditorTemplateSORNumCategories,

    // Template creator
    templateCreatorname,
    templateCreatorFCCreatedReporter,
    templateCreatorEAQCreatedReporter,
    templateCreatorMCQCreatedReporter,
    templateCreatorSORCreatedReporter,



    regularMainMenuChoicesDisplay,
    studyToolEditMenuChoicesDisplay,

    quizSaved,
    scoreReporter,
    studySessionEndedReporter,
    correctReporter,
    incorrectReporter,
    templateDeletedReporter,
    invalidInputReporter,
    templateEditedReporter,

    noStudyToolToEditSorrier,
    noStudyToolToStudySorrier,
    noTemplateToChooseSorrier,
    noStudyToolToDeleteSorrier,
    noStudyToolToUndeleteSorrier,

    // Log in items
    welcomer,
    introduceWelcomer,
    chooseNewWelcomer,
    introduceExiter,
    chooseNewExiter,
    welcomerOrExiterPrompt,
    logInUserNamePrompt,
    logInPasswordPrompt,
    logInMenu,
    logInAdminKeyPrompt,
    logInIncorrectAdminKey,
    logInCreateAccountError,
    logInAccountSuspended,
    logInCreateUserNamePrompt,
    logInCreatePasswordPrompt,
    logInCreateEmailPrompt,
    logInUsernameResetPrompt,
    logInResetAccountPrompt,
    logInProvideNewPinPrompt,
    logInInvalidPinPrompt,
    logInSayUsernameNotUnique,
    logInSaySuccessfulAccountCreation,
    logInTrialNamePrompt,
    logInSayTrialStarted,
    logInSayLoginSuccess,
    logInSayPasswordChangeSuccess,
    logInSayLoginError,
    logInSayUserName,
    logInSayUserID,
    logInSayUserType,
    logInSaveOrNotPrompt,
    logInTypeOfAccountMenu,
    logInUserNotExist,
    logInExiter,

    // admin specific
    adminMainMenuDisplay,
    templateMenu,
    editTemplateMenuFC,
    editTemplateMenuMCQ,
    editTemplateMenuSOR,
    createTemplateMenu,
    currentlyFrozen,
    days,
    currentlyNotFrozen,
    changeFreezeStatusPrompt,
    freezeAccountsForHowManyDaysPrompt,
    userHandlingMenu,
    editAdminKeyPrompt,
    introduceAdminKey,
    newAdminKeyPrompt,

    // Study tool display
    studyToolDisplayName,
    studyToolDisplayID,
    studyToolDisplayAuthor,
    studyToolDisplayAccessibility,
    studyToolDisplayCurrQA,
    studyToolDisplayQuestion,
    studyToolDisplayAnswer,
    studyToolDisplayAnswerIs,
    studyToolDisplayVisibleStudyTools,
    studyToolDisplayAllStudyTools,
    studyToolDisplayOwnedStudyTools,
    studyToolDisplayOwnedDeletedStudyTools,
    ranOutOfTime,

    // Template display
    templateDisplayername,
    templateDisplayerid,
    templateDisplayertype,
    templateDisplayerisTimed,
    templateDisplayertimedPerQuestionNotQuiz,
    templateDisplayertimeLimit,
    templateDisplayerisScored,
    templateDisplayerwordsReappear,
    templateDisplayershowCorrectAnswerAfterQuestion,
    templateDisplayershowCorrectAnswersAfterQuiz,
    templateDisplayernumCategories,
    templateDisplayerTemplates,

    // Collaboration
    getMCAnswerPrompt,
    getSORAnswerPrompt,
    illegalAnswerReporter,
    studyToolDisplayInvitedStudyTools,
    collaborateStudyToolIDPrompt,
    collaboratorNameWithQuitPrompt,
    sayCollaboratorAdded,
    sayStudyToolNotExistOrNotYours,
    collabMenu, sayCollaboratorRemoved,
    displayAllCollaborators,
    noCollaboratorsExist,

    // user display
    userDisplayerUsers,
    userID,
    name,
    suspended,
    frozen,
    suspendedFor,
    lastLogIn,

    // Version control
    editTime,
    editorName,
    editHistory,
    revertVersionWithQuitPrompt,
    sayStudyToolVersionReverted,
}
